import { GOLD_PACKS, MODULES, PLANES, Profile, Upgrade, planeStats, researchLevel, researchXp, upgradeLevel, MAX_UPGRADE_LEVEL, upgradeSilver, planeUnlocked, planeLockedReason, CAREER_STAGES, careerStage, ZONE, ownedModules, equippedModule } from '../shared/data';
import { operationPlan } from '../shared/operations';
import { PHASE_SKILL } from '../shared/skills';
import { icon, IconName } from './icons';
import { hasPremium, premiumExpiresAt, PREMIUM_PRODUCT_ID } from '../shared/premium';
import { PHOENIX_PART_LEVELS, phoenixPartRequirements } from '../shared/phoenix';

const money = (n: number) => Math.floor(n).toLocaleString('ru-RU');
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x]!));
const aircraft = (id: string, cls = '') => '<canvas class="' + cls + '" data-aircraft="' + id + '" width="400" height="200" role="img" aria-label="' + PLANES.find(x => x.id === id)!.name + '"></canvas>';

export function renderLobby(p: Profile, resume: boolean, level: number, completed = 0) {
  const model = PLANES.find(x => x.id === p.selected)!;
  const stage = careerStage(level);
  const stages = CAREER_STAGES.map(s => {
    const current = stage.number === s.number, complete = s.number < stage.number, locked = !current && !complete;
    const state = current ? 'current' : complete ? 'complete' : 'locked';
    const description = 'Этап ' + s.number + ' из ' + CAREER_STAGES.length + ', уровни ' + s.start + '–' + s.end + ': ' + (current ? 'текущий' : complete ? 'пройден' : 'закрыт. Пройдите предыдущий этап: босс ' + (s.start - 1));
    return '<article class="swiper-slide career-stage ' + state + '" aria-label="' + description + '" title="' + description + '" ' + (current ? 'aria-current="step"' : '') + '><b>Этап ' + s.number + (locked ? '<span class="career-lock">' + icon('lock') + '</span>' : '') + '</b><span>Уровни ' + s.start + '–' + s.end + '</span><small>' + (complete && !current ? icon('check') + ' Пройден' : 'Босс ' + s.end + (current ? ' · текущий' : ' · Закрыт')) + '</small></article>';
  }).join('');
  const route = '<section class="career-route" aria-label="Этапы кампании"><header class="career-route-heading"><div><h2>Этапы кампании</h2><small>Карта прогресса · босс в конце этапа</small></div><div class="career-navigation"><button class="career-prev" aria-label="Предыдущие этапы">' + icon('arrowLeft') + '</button><button class="career-next" aria-label="Следующие этапы">' + icon('arrow') + '</button></div></header><div class="swiper career-swiper" data-current="' + (stage.number - 1) + '"><div class="swiper-wrapper">' + stages + '</div></div></section>';
  return '<section class="launch-screen" aria-label="Выбор режима">' +
    '<button class="launch-aircraft" data-tab="fleet" aria-label="Сменить самолёт: ' + model.name + '">' + aircraft(model.id) + '<span><b>' + model.name + '</b><small>Сменить самолёт ' + icon('arrow') + '</small></span></button>' +
    '<div class="launch-modes"><button class="launch-mode campaign" data-action="pve" aria-label="Играть: Кампания"><span class="mode-mark">' + icon('route') + '</span><strong>Кампания</strong><small>Уровень ' + level + ' / ' + ZONE.length + ' · вылеты ' + Math.min(completed, operationPlan(level).sorties) + '/' + operationPlan(level).sorties + '</small><span class="launch-cta">' + (resume ? 'Продолжить' : 'Играть') + icon('arrow') + '</span></button>' +
    '<button class="launch-mode versus" data-action="queue" aria-label="Играть: Один на один"><span class="mode-mark">' + icon('duel') + '</span><strong>Один на один</strong><small>Дуэль</small><span class="launch-cta">Играть' + icon('arrow') + '</span></button></div>' + route + '<button class="flight-help" data-tab="help">' + icon('help') + '<span>Как летать</span>' + icon('arrow') + '</button></section>';
}

export function renderHangar(p: Profile, inspected: string) {
  const model = PLANES.find(x => x.id === inspected) ?? PLANES.find(x => x.id === p.selected)!;
  const owned = p.owned.includes(model.id), selected = p.selected === model.id;
  const stats = planeStats({ ...p, selected: model.id });
  const priceIcon = model.currency === 'gold' ? 'gold' : 'silver';
  const bossLocked = !planeUnlocked(p, model), affordable = p[model.currency] >= model.price;
  const availability = (plane: typeof PLANES[number]) => p.owned.includes(plane.id) ? 'owned' : !planeUnlocked(p,plane) ? 'locked' : p[plane.currency] < plane.price ? 'shortfall' : 'available';
  const status = availability(model);
  const statusLabel = (plane: typeof PLANES[number]) => {
    const state = availability(plane);
    return state === 'owned' ? icon('check') + (p.selected === plane.id ? ' Выбран' : ' В ангаре') : state === 'locked' ? icon('lock') + ' Босс ' + plane.unlockBoss : state === 'shortfall' ? icon(plane.currency) + ' Не хватает ' + (plane.currency === 'gold' ? 'золота' : 'серебра') : icon('check') + ' Можно купить';
  };
  const collection = PLANES.map(plane => {
    const has = p.owned.includes(plane.id), state = availability(plane);
    return '<button class="aircraft-pick fleet-' + state + ' ' + (plane.id === model.id ? 'viewed' : '') + '" data-inspect="' + plane.id + '" aria-pressed="' + (plane.id === model.id) + '" aria-label="' + (has ? 'Выбрать и настроить ' : 'Посмотреть ') + plane.name + (state === 'locked' ? ': закрыт, победите босса ' + plane.unlockBoss : state === 'shortfall' ? ': не хватает ресурсов' : state === 'available' ? ': можно купить' : ': в ангаре') + '">' + aircraft(plane.id) + '<b>' + plane.name + '</b><span class="fleet-state">' + statusLabel(plane) + '</span>' + (!has ? '<small class="fleet-price">' + icon(plane.currency) + ' ' + money(plane.price) + '</small>' : '') + '</button>';
  }).join('');
  const specs: [IconName, string, string][] = [['armor', 'Прочность', Math.round(stats.hp) + ' HP'], ['engine', 'Скорость', Math.round(stats.speed) + ''], ['turnRight', 'Манёвр', Math.round(stats.turn * 180 / Math.PI) + '°/с'], ['target', 'Урон', stats.damage.toFixed(1).replace('.0', '')]];
  const current = planeStats(p), compared = [stats.hp/current.hp,stats.speed/current.speed,stats.turn/current.turn,stats.damage/current.damage];
  const branches: [Upgrade, IconName, string, string][] = [['hull', 'armor', 'Броня', '+2% прочности за ступень · до +30%'], ['engine', 'engine', 'Двигатель', 'До +10% скорости и +5% манёвра'], ['gun', 'target', 'Вооружение', '+2% урона за ступень · до +30%']];
  const improvements = branches.map(([branch, symbol, name, detail]) => {
    if (model.id === 'skate') {
      const part = phoenixPartRequirements(p, branch);
      const benefit = branch === 'hull' ? 'Прочность ' + money(part.before.hp) + ' → ' + money(part.after.hp) + ' HP' : branch === 'engine' ? 'Скорость ' + money(part.before.speed) + ' → ' + money(part.after.speed) + ' · манёвр ' + Math.round(part.after.turn * 180 / Math.PI) + '°/с' : 'Урон ' + part.before.damage.toFixed(1) + ' → ' + part.after.damage.toFixed(1);
      const reason = part.maxed ? 'Все детали установлены' : !part.bossDefeated ? 'Сначала победите босса ' + part.bossLevel : !part.affordable ? 'Не хватает ' + money(part.price - p.gold) + ' золота' : 'Открыто · без опыта и серебра';
      return '<section class="improvement phoenix-part"><span class="improvement-icon">' + icon(symbol) + '</span><div><h3>' + name + '</h3><small>' + (part.maxed ? 'Максимальная золотая деталь' : benefit) + '</small></div><span class="upgrade-level">' + part.current + '/' + PHOENIX_PART_LEVELS + '</span><div class="upgrade-steps" aria-hidden="true">' + Array.from({length:PHOENIX_PART_LEVELS},(_,i)=>'<i class="' + (i<part.current?'filled':'') + '"></i>').join('') + '</div><button class="button gold-button" data-phoenix-part="' + branch + '" data-level="' + part.level + '" ' + (!part.canBuy ? 'disabled' : '') + '>' + (part.maxed ? icon('check') + ' Максимум' : !part.bossDefeated ? icon('lock') + ' Босс ' + part.bossLevel : 'Установить · ' + icon('gold') + ' ' + part.price) + '</button>' + (!part.maxed ? '<span class="upgrade-price gold">' + icon('gold') + ' ' + part.price + ' · золотая деталь ' + part.level + '</span>' : '') + '<span class="upgrade-status ' + (part.canBuy ? 'ready' : '') + '">' + reason + '</span></section>';
    }
    const n = upgradeLevel(p, model.id, branch), level = n + 1, cost = upgradeSilver(level, model.id), xp = researchXp(level, model.id);
    const researched = researchLevel(p, model.id, branch) >= level;
    const locked = !owned || !selected || n >= MAX_UPGRADE_LEVEL || (researched ? p.silver < cost : p.xp < xp);
    const action = n >= MAX_UPGRADE_LEVEL ? 'Максимум' : researched ? '<span class="silver">' + icon('silver') + ' ' + money(cost) + '</span> · Купить' : '<span class="xp">' + icon('xp') + ' ' + xp + ' XP</span> · Исследовать';
    const status = n >= MAX_UPGRADE_LEVEL ? 'Ветка полностью улучшена' : !selected ? 'Выберите этот самолёт для улучшения' : researched ? p.silver < cost ? 'Не хватает ' + money(cost - p.silver) + ' серебра' : 'Исследовано · можно купить' : p.xp < xp ? 'Не хватает ' + money(xp - p.xp) + ' опыта' : 'Сначала исследуйте, затем купите';
    return '<section class="improvement"><span class="improvement-icon">' + icon(symbol) + '</span><div><h3>' + name + '</h3><small>' + detail + '</small></div><span class="upgrade-level">' + n + '/' + MAX_UPGRADE_LEVEL + '</span><div class="upgrade-steps" aria-hidden="true">' + Array.from({length:MAX_UPGRADE_LEVEL}, (_,i) => '<i class="' + (i<n?'filled':'') + '"></i>').join('') + '</div><button class="button" data-' + (researched?'upgrade':'research') + '="' + branch + '" data-level="' + level + '" ' + (locked?'disabled':'') + '>' + (locked && n < MAX_UPGRADE_LEVEL ? icon('lock') : '') + action + '</button>' + (n<MAX_UPGRADE_LEVEL?'<span class="upgrade-price">' + (researched ? 'Этап 2 из 2 · покупка' : 'Этап 1 из 2 · исследование. Покупка: <span class="silver">' + icon('silver') + ' ' + money(cost) + '</span>') + '</span>':'') + '<span class="upgrade-status ' + (!locked ? 'ready' : '') + '">' + status + '</span></section>';
  }).join('');
  const equipment = MODULES.map(module => {
    const has = ownedModules(p, model.id).includes(module.id), active = equippedModule(p, model.id) === module.id;
    return '<section class="equipment-card ' + (active ? 'equipped' : '') + '"><span class="equipment-icon">' + icon(module.id === 'carburetor' ? 'engine' : 'cooling') + '</span><div><h3>' + module.name + '</h3><p>' + module.detail + '</p><small>' + (has ? 'Куплен для ' + model.name : p.gold < module.price ? 'Не хватает ' + money(module.price - p.gold) + ' золота' : 'Покупка только для ' + model.name) + '</small></div><button class="button ' + (has ? 'subtle' : 'gold-button') + '" data-' + (has ? 'module-equip' : 'module-buy') + '="' + (active ? '' : module.id) + '" data-model="' + model.id + '" ' + (!has && p.gold < module.price ? 'disabled' : '') + '>' + (has ? active ? icon('check') + ' Снять' : 'Установить' : '<span class="gold">' + icon('gold') + ' ' + module.price + '</span> · Купить') + '</button></section>';
  }).join('');
  return '<div class="page-heading"><h1>Самолёты</h1><span class="rank-note xp">Опыт: ' + money(p.xp) + '</span></div><div class="aircraft-collection" aria-label="Самолёты ангара">' + collection + '</div>' +
    '<section class="aircraft-detail fleet-' + status + '"><div class="detail-portrait" style="--plane-color:' + model.color + '">' + aircraft(model.id) + '</div><div class="detail-info"><div class="detail-title"><h2>' + model.name + '</h2><span class="model-badge">' + (model.currency === 'gold' ? 'За золото' : model.unlockBoss ? 'Босс ' + model.unlockBoss : 'Стартовый') + '</span></div><p>' + model.role + '</p><p class="fleet-detail-state">' + statusLabel(model) + '</p><div class="aircraft-specs">' + specs.map(([symbol, label, value], i) => '<div>' + icon(symbol) + '<small>' + label + '</small><b>' + value + '</b>' + (!owned ? '<small class="stat-comparison">' + (compared[i]>=1?'+':'') + Math.round((compared[i]-1)*100) + '% к вашему</small>' : '') + '</div>').join('') + '</div>' +
    (owned ? '<button class="button subtle detail-action" data-tab="play">К вылету ' + icon('arrow') + '</button>' : '<button class="button ' + (model.currency === 'gold' ? 'gold-button' : '') + ' detail-action fleet-purchase fleet-' + status + '" data-buy="' + model.id + '" ' + (bossLocked || !affordable ? 'disabled' : '') + '>' + (bossLocked ? icon('lock') + ' Закрыт · босс ' + model.unlockBoss : !affordable ? icon('lock') + ' Недостаточно ресурсов' : 'Купить · <span class="' + model.currency + '">' + icon(priceIcon) + ' ' + money(model.price) + '</span>') + '</button><small class="purchase-note">' + (bossLocked ? escapeHtml(planeLockedReason(p, model)) : !affordable ? 'Не хватает ' + money(model.price - p[model.currency]) + ' ' + (model.currency === 'gold' ? 'золота' : 'серебра') : 'Самолёт останется в вашем ангаре') + '</small>' + (model.currency === 'gold' && !affordable ? '<button class="plain" data-tab="store">Пополнить золото ' + icon('arrow') + '</button>' : '')) + '</div></section>' +
    (owned ? '<div class="subheading"><h2>' + (model.id === 'skate' ? 'Золотые детали' : 'Улучшения') + '</h2><span>' + (model.id === 'skate' ? 'Открываются после боссов · покупка за золото' : 'Исследовать за опыт → купить за серебро') + '</span></div><div class="improvement-grid">' + improvements + '</div><div class="subheading"><h2>Оснащение</h2><span>Для самолёта «' + model.name + '» · один активный модуль</span></div><div class="equipment-grid">' + equipment + '</div>' : '<p class="locked-improvements">Улучшения и оснащение доступны после покупки самолёта.</p>');
}

export function renderSkills(p: Profile) {
  const owned = p.skills?.phase, unlocked = p.defeatedBosses?.includes(PHASE_SKILL.unlockBoss), missingSilver = Math.max(0, PHASE_SKILL.silver - p.silver), missingXp = Math.max(0, PHASE_SKILL.xp - p.xp);
  const reason = !unlocked ? 'Откроется после победы над боссом 10' : [missingSilver ? money(missingSilver) + ' серебра' : '', missingXp ? money(missingXp) + ' опыта' : ''].filter(Boolean).join(' и ');
  return '<div class="page-heading"><h1>Активные навыки</h1></div><p class="skills-intro">Одна покупка для всего профиля. Работают на любом самолёте в кампании.</p><section class="skill-card"><span class="skill-art">' + icon('layers') + '</span><span class="eyebrow">ФАЗОВЫЙ ПРОХОД</span><h2>Сквозь препятствия</h2><p>2 секунды сквозь скалы, ПВО и самолёты. Перезарядка 35 секунд. Пули, бомбы и земля остаются опасными.</p>' + (owned ? '<p class="skill-owned">' + icon('check') + ' Открыт для всех самолётов · E или кнопка в бою</p>' : '<button class="button" data-skill-buy="phase" ' + (!unlocked || missingSilver || missingXp ? 'disabled' : '') + '>Открыть · <span class="silver">' + icon('silver') + ' 1200</span> + <span class="xp">' + icon('xp') + ' 300 XP</span></button><p class="upgrade-status">' + (!unlocked ? reason : reason ? 'Не хватает ' + reason : 'Доступно для покупки') + '</p>') + '</section>';
}

type StoreState = { available: boolean; authorized: boolean; platformAvailable: boolean; products: { id: string; price: string }[] };
export function renderStore(p: Profile, state: StoreState) {
  const premium = state.products.find(product => product.id === PREMIUM_PRODUCT_ID), active = hasPremium(p);
  const expires = premiumExpiresAt(p), until = expires ? new Date(expires).toLocaleString('ru-RU', {day:'numeric', month:'long', year:'numeric', hour:'2-digit', minute:'2-digit'}) : '';
  const premiumCard = '<section class="premium-offer ' + (active ? 'active' : '') + '" aria-label="Премиум-доступ"><span class="premium-emblem">' + icon('trophy') + '</span><div><span class="eyebrow">ПРИВИЛЕГИИ ПИЛОТА · 30 ДНЕЙ</span><h2>Премиум-доступ</h2><div class="premium-perks"><span class="xp">' + icon('xp') + ' +50% опыта</span><span class="silver">' + icon('silver') + ' +50% серебра</span><span class="ad-free">' + icon('noAds') + ' Без рекламы</span><span>' + icon('target') + ' Безлимит на боссах</span></div><p>Увеличивает опыт и серебро за бои в кампании и дуэлях и отключает рекламу на весь срок премиума. Даёт неограниченные попытки на боссах: после поражений вы остаётесь у босса, без возврата к началу этапа. Действует на весь профиль, для любого самолёта.</p><small>Повторная покупка добавляет 30 дней к оставшемуся сроку. Автопродления нет.</small></div><div class="premium-purchase">' + (active ? '<b>' + icon('check') + ' Активен до ' + until + '</b>' : expires ? '<small>Срок завершён: ' + until + '</small>' : '') + '<button class="button gold-button" data-pack="premium" ' + (!state.available || !premium ? 'disabled' : '') + '>' + (premium ? (active ? 'Продлить на 30 дней · ' : 'Купить на 30 дней · ') + escapeHtml(premium.price) : 'Пока недоступно') + '</button><small>+50% к боевым наградам · без рекламы · безлимит на боссах</small></div></section>';
  const goldCards = GOLD_PACKS.map(pack => {
    const product = state.products.find(x => x.id === pack.id);
    return '<section class="gold-pack"><div>' + icon('gold') + '</div><h2>' + pack.gold + '</h2><small>золота</small><button class="button gold-button" data-pack="' + pack.id + '" ' + (!state.available || !product ? 'disabled' : '') + '>' + (product ? escapeHtml(product.price) : 'Недоступно') + '</button></section>';
  }).join('');
  return '<div class="page-heading"><h1>Магазин</h1></div>' + premiumCard + '<h2 class="store-title">Золото</h2>' + (!state.available ? '<p class="store-notice">Покупки пока недоступны.</p>' : '') +
    (state.platformAvailable && !state.authorized ? '<button class="plain" data-action="authorize">Войти в Яндекс для покупок ' + icon('arrow') + '</button>' : '') +
    '<div class="store-grid">' + goldCards + '</div>' + (state.available ? '<button class="plain" data-action="recover">Восстановить покупки</button>' : '') +
    '<div class="subheading"><h2>Переплавка золота</h2></div><p class="exchange-rate">1 золото = 25 серебра или 8 опыта</p><div class="exchange-grid">' + [10, 50, 100].map(amount => '<section class="exchange-card"><b>' + icon('gold') + ' ' + amount + '</b><button class="plain" data-exchange="' + amount + '" data-currency="silver" ' + (p.gold < amount ? 'disabled' : '') + '>' + icon('arrow') + ' <span class="silver">' + icon('silver') + ' ' + money(amount * 25) + '</span>' + '</button><button class="plain" data-exchange="' + amount + '" data-currency="xp" ' + (p.gold < amount ? 'disabled' : '') + '>' + icon('arrow') + ' ' + amount * 8 + ' опыта</button></section>').join('') + '</div>';
}
